name: flashx
description: cross platform mobile app to get information about the next rocket launch, upcoming rocket launches and past rocket launches. SpaceX designs, manufactures and launches rockets and spacecraft.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.0-262.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  responsive_framework: ^0.1.5
  flutter_bloc: ^7.3.2
  shared_preferences: ^2.0.8
  http: ^0.13.4
  flutter_countdown_timer: ^4.1.0
  intl: ^0.17.0
  url_launcher: ^6.0.15
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: D-din
      fonts:
        - asset: fonts/d-din/D-DINExp.otf
          weight: 400
        - asset: fonts/d-din/D-DINExp-Bold.otf
          weight: 700
        - asset: fonts/d-din/D-DINExp-Italic.otf
          weight: 400